/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSocialAdsRouteImport } from './routes/servicios.social-ads'
import { Route as ServiciosSeoRouteImport } from './routes/servicios.seo'
import { Route as ServiciosRedesSocialesRouteImport } from './routes/servicios.redes-sociales'
import { Route as ServiciosGrabacionContenidoRouteImport } from './routes/servicios.grabacion-contenido'
import { Route as ServiciosEmailMarketingRouteImport } from './routes/servicios.email-marketing'
import { Route as ServiciosDesarrolloWebRouteImport } from './routes/servicios.desarrollo-web'
import { Route as ServiciosContenidoRouteImport } from './routes/servicios.contenido'
import { Route as ServiciosCaptacionRouteImport } from './routes/servicios.captacion'
import { Route as ServiciosBrandingCompletoRouteImport } from './routes/servicios.branding-completo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSocialAdsRoute = ServiciosSocialAdsRouteImport.update({
  id: '/servicios/social-ads',
  path: '/servicios/social-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSeoRoute = ServiciosSeoRouteImport.update({
  id: '/servicios/seo',
  path: '/servicios/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRedesSocialesRoute = ServiciosRedesSocialesRouteImport.update({
  id: '/servicios/redes-sociales',
  path: '/servicios/redes-sociales',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosGrabacionContenidoRoute =
  ServiciosGrabacionContenidoRouteImport.update({
    id: '/servicios/grabacion-contenido',
    path: '/servicios/grabacion-contenido',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiciosEmailMarketingRoute = ServiciosEmailMarketingRouteImport.update({
  id: '/servicios/email-marketing',
  path: '/servicios/email-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosDesarrolloWebRoute = ServiciosDesarrolloWebRouteImport.update({
  id: '/servicios/desarrollo-web',
  path: '/servicios/desarrollo-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosContenidoRoute = ServiciosContenidoRouteImport.update({
  id: '/servicios/contenido',
  path: '/servicios/contenido',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCaptacionRoute = ServiciosCaptacionRouteImport.update({
  id: '/servicios/captacion',
  path: '/servicios/captacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosBrandingCompletoRoute =
  ServiciosBrandingCompletoRouteImport.update({
    id: '/servicios/branding-completo',
    path: '/servicios/branding-completo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicios/branding-completo': typeof ServiciosBrandingCompletoRoute
  '/servicios/captacion': typeof ServiciosCaptacionRoute
  '/servicios/contenido': typeof ServiciosContenidoRoute
  '/servicios/desarrollo-web': typeof ServiciosDesarrolloWebRoute
  '/servicios/email-marketing': typeof ServiciosEmailMarketingRoute
  '/servicios/grabacion-contenido': typeof ServiciosGrabacionContenidoRoute
  '/servicios/redes-sociales': typeof ServiciosRedesSocialesRoute
  '/servicios/seo': typeof ServiciosSeoRoute
  '/servicios/social-ads': typeof ServiciosSocialAdsRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicios/branding-completo': typeof ServiciosBrandingCompletoRoute
  '/servicios/captacion': typeof ServiciosCaptacionRoute
  '/servicios/contenido': typeof ServiciosContenidoRoute
  '/servicios/desarrollo-web': typeof ServiciosDesarrolloWebRoute
  '/servicios/email-marketing': typeof ServiciosEmailMarketingRoute
  '/servicios/grabacion-contenido': typeof ServiciosGrabacionContenidoRoute
  '/servicios/redes-sociales': typeof ServiciosRedesSocialesRoute
  '/servicios/seo': typeof ServiciosSeoRoute
  '/servicios/social-ads': typeof ServiciosSocialAdsRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicios/branding-completo': typeof ServiciosBrandingCompletoRoute
  '/servicios/captacion': typeof ServiciosCaptacionRoute
  '/servicios/contenido': typeof ServiciosContenidoRoute
  '/servicios/desarrollo-web': typeof ServiciosDesarrolloWebRoute
  '/servicios/email-marketing': typeof ServiciosEmailMarketingRoute
  '/servicios/grabacion-contenido': typeof ServiciosGrabacionContenidoRoute
  '/servicios/redes-sociales': typeof ServiciosRedesSocialesRoute
  '/servicios/seo': typeof ServiciosSeoRoute
  '/servicios/social-ads': typeof ServiciosSocialAdsRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/diagnostico'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/servicios/branding-completo'
    | '/servicios/captacion'
    | '/servicios/contenido'
    | '/servicios/desarrollo-web'
    | '/servicios/email-marketing'
    | '/servicios/grabacion-contenido'
    | '/servicios/redes-sociales'
    | '/servicios/seo'
    | '/servicios/social-ads'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/diagnostico'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/servicios/branding-completo'
    | '/servicios/captacion'
    | '/servicios/contenido'
    | '/servicios/desarrollo-web'
    | '/servicios/email-marketing'
    | '/servicios/grabacion-contenido'
    | '/servicios/redes-sociales'
    | '/servicios/seo'
    | '/servicios/social-ads'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/diagnostico'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/servicios/branding-completo'
    | '/servicios/captacion'
    | '/servicios/contenido'
    | '/servicios/desarrollo-web'
    | '/servicios/email-marketing'
    | '/servicios/grabacion-contenido'
    | '/servicios/redes-sociales'
    | '/servicios/seo'
    | '/servicios/social-ads'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServiciosBrandingCompletoRoute: typeof ServiciosBrandingCompletoRoute
  ServiciosCaptacionRoute: typeof ServiciosCaptacionRoute
  ServiciosContenidoRoute: typeof ServiciosContenidoRoute
  ServiciosDesarrolloWebRoute: typeof ServiciosDesarrolloWebRoute
  ServiciosEmailMarketingRoute: typeof ServiciosEmailMarketingRoute
  ServiciosGrabacionContenidoRoute: typeof ServiciosGrabacionContenidoRoute
  ServiciosRedesSocialesRoute: typeof ServiciosRedesSocialesRoute
  ServiciosSeoRoute: typeof ServiciosSeoRoute
  ServiciosSocialAdsRoute: typeof ServiciosSocialAdsRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/social-ads': {
      id: '/servicios/social-ads'
      path: '/servicios/social-ads'
      fullPath: '/servicios/social-ads'
      preLoaderRoute: typeof ServiciosSocialAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/seo': {
      id: '/servicios/seo'
      path: '/servicios/seo'
      fullPath: '/servicios/seo'
      preLoaderRoute: typeof ServiciosSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/redes-sociales': {
      id: '/servicios/redes-sociales'
      path: '/servicios/redes-sociales'
      fullPath: '/servicios/redes-sociales'
      preLoaderRoute: typeof ServiciosRedesSocialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/grabacion-contenido': {
      id: '/servicios/grabacion-contenido'
      path: '/servicios/grabacion-contenido'
      fullPath: '/servicios/grabacion-contenido'
      preLoaderRoute: typeof ServiciosGrabacionContenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/email-marketing': {
      id: '/servicios/email-marketing'
      path: '/servicios/email-marketing'
      fullPath: '/servicios/email-marketing'
      preLoaderRoute: typeof ServiciosEmailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/desarrollo-web': {
      id: '/servicios/desarrollo-web'
      path: '/servicios/desarrollo-web'
      fullPath: '/servicios/desarrollo-web'
      preLoaderRoute: typeof ServiciosDesarrolloWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/contenido': {
      id: '/servicios/contenido'
      path: '/servicios/contenido'
      fullPath: '/servicios/contenido'
      preLoaderRoute: typeof ServiciosContenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/captacion': {
      id: '/servicios/captacion'
      path: '/servicios/captacion'
      fullPath: '/servicios/captacion'
      preLoaderRoute: typeof ServiciosCaptacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/branding-completo': {
      id: '/servicios/branding-completo'
      path: '/servicios/branding-completo'
      fullPath: '/servicios/branding-completo'
      preLoaderRoute: typeof ServiciosBrandingCompletoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServiciosBrandingCompletoRoute: ServiciosBrandingCompletoRoute,
  ServiciosCaptacionRoute: ServiciosCaptacionRoute,
  ServiciosContenidoRoute: ServiciosContenidoRoute,
  ServiciosDesarrolloWebRoute: ServiciosDesarrolloWebRoute,
  ServiciosEmailMarketingRoute: ServiciosEmailMarketingRoute,
  ServiciosGrabacionContenidoRoute: ServiciosGrabacionContenidoRoute,
  ServiciosRedesSocialesRoute: ServiciosRedesSocialesRoute,
  ServiciosSeoRoute: ServiciosSeoRoute,
  ServiciosSocialAdsRoute: ServiciosSocialAdsRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
